#! usr/bin/env python
#coding:utf-8


class PersonClass:
    def __init__(self,name):
        self.name = name
    def getName(self):
        return  self.name
    def getColor(self):
        return "Yellow"
if __name__ == "__main__" :
  Brain = PersonClass("Brain")
  print(Brain.getName())
  print(Brain.getColor())
