#!/usr/bin/env python
#coding:utf-8

#list 的重要几个函数用法
a = [1,2,3]
c = [1,2,3]
b = [4,5,6]

a.extend(b) #把b列表的元素追加到a列表中
c.append(b) #把b列表当作一个元素追加到c列表中
b.insert(1,7) #在b列表中的索引为1的地方，增加元素7
print("List a is " + str(a))
print("List c is " + str(c))
print("List b is " + str(b))
print("a.index(2) 的索引 is " + str(a.index(2)))  #index读取a列表中元素2的索引是多少
a.pop(1)#pop是根据索引来删除列表元素，但是如果函数中没填写索引号，那么就会默认删除所有的，剩下列表最后一个元素
print("a.pop(1) 后list a 为" + str(a))
c.remove(1)#remove是根据元素值来删除列表元素。要注意找不到值异常问题，需要捕捉异常。
print("c.remove(1) 后List c is " + str(c))
a.reverse() # reverse是把列表反转排列
print("a.reverse() 后list a 为" + str(a))
a.sort()#把列表的元素进行排列。
print("a.sort() 后list a 为" + str(a))

运行结果：
List a is [1, 2, 3, 4, 5, 6]
List c is [1, 2, 3, [4, 7, 5, 6]]
List b is [4, 7, 5, 6]
a.index(2) 的索引 is 1
a.pop(1) 后list a 为[1, 3, 4, 5, 6]
c.remove(1) 后List c is [2, 3, [4, 7, 5, 6]]
a.reverse() 后list a 为[6, 5, 4, 3, 1]
a.sort() 后list a 为[1, 3, 4, 5, 6]
